# GoHub 配置文件

# 版本信息
version: "1.0.0"

# 服务器配置
server:
  addr: ":8080"                       # 服务监听地址
  read_timeout: 3m                    # 读取超时
  write_timeout: 3m                   # 写入超时
  read_buffer_size: 4096              # 读缓冲区大小(bytes)
  write_buffer_size: 4096             # 写缓冲区大小(bytes)
  message_buffer_cap: 256             # 消息缓冲队列容量

# 集群配置
cluster:
  enabled: false

# 认证配置
auth:
  enabled: true
  secret_key: "test-secret-key-change-this-in-production"
  issuer: "gohub"
  allow_anonymous: true 